### ISSUE TITLE
QWidget not found on Ubuntu 14.04

### ISSUE THREAD

**Issue by kopp** [lucasw/rqt_mypkg#4]
Using the python example, I get the following error after compiling the package with catkin with package `ros-jade-python-qt-binding` of version `0.2.19-0trusty-20160702-043937-0700`:

_Edit_: It turns out, that the files installed actually came from packet version `0.2.16-0trusty-20150521-0314-+0000`. Upgrading to that version removed the issue.

``` sh
% rosrun rqt_mypkg rqt_mypkg
Traceback (most recent call last):
  File "/home/foo/catkin_ws2/src/rqt_example_py/scripts/rqt_mypkg", line 5, in <module>
    from rqt_mypkg.my_module import MyPlugin
  File "/home/foo/catkin_ws2/src/rqt_example_py/src/rqt_mypkg/my_module.py", line 7, in <module>
    from python_qt_binding.QtWidgets import QWidget
ImportError: No module named QtWidgets
```

It can be solved by changing

```
from python_qt_binding.QtWidgets import QWidget
```

to

```
from python_qt_binding.QtGui import QWidget
```

i.e. by using the following patch:

``` patch
diff --git a/rqt_example_py/src/rqt_mypkg/my_module.py b/rqt_example_py/src/
index 2f96ca1..275b9f9 100644
--- a/rqt_example_py/src/rqt_mypkg/my_module.py
+++ b/rqt_example_py/src/rqt_mypkg/my_module.py
@@ -4,7 +4,7 @@ import rospy

 from qt_gui.plugin import Plugin
 from python_qt_binding import loadUi
-from python_qt_binding.QtWidgets import QWidget
+from python_qt_binding.QtGui import QWidget

 class MyPlugin(Plugin):

```

**Comment by lucasw** [comment]
You could also check out 35ec246458d28c7ff9357422b7acb992acc59a5c prior to the merge in #2 .  I tested that on jade and kinetic on ubuntu 14.04 and 16.04 respectively, and there is a report there of working in indigo- is there a newer version of python_qt_binding you can update to?

**Comment by lucasw** [comment]
https://github.com/ros-gbp/python_qt_binding-release/blob/master/tracks.yaml#L64 I think is saying 0.2.19 is the newest jade version, so I'm not sure why there is a discrepancy here.

**Comment by kopp** [comment]
My bad.  It looks like I actually had the files of version `0.2.16-0trusty-20150521-0314-+0000` of `ros-jade-python-qt-binding` installed on my system, but `apt` reported the version wrong.  Probably because something bad happened to the files (manually overwritten?)...  Manually upgrading to `0.2.19-0trusty-20160702-043937-0700` removed the issue.  Sorry to bother you and thank you for your help.
